### ISSUE TITLE
RFC - Restore Date.now to the original implementation

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/jest-mock-now#2]
# Description

as per @just-boris 's [comment](https://twitter.com/MicheleBertoli/status/878529383673331712), it would be nice to have the ability to restore `Date.now` to the [original implementation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now); below a possible solution to this problem that takes advantage of the `mockFn.mockRestore()` [function](https://facebook.github.io/jest/docs/mock-function-api.html#mockfnmockrestore).

## Code

```javascript
const { NOW } = require('./constants');

module.exports = date => {
  const now = date ? date.getTime() : NOW;
  Date.now = jest.spyOn(Date, 'now')
    .mockImplementation(() => now);
};
```

## Test

```javascript
test('Date.now as a mock function exposes mockRestore()', () => {
  const mocked = Date.now(); // 1498089600000
  Date.now.mockRestore();
  const real = Date.now(); // 1498331373659
  expect(real).toBeGreaterThan(mocked);
});
```

**Comment by MicheleBertoli** [comment]
I was wondering if it would be better to hide the Jest internals (i.e. `mockRestore`) from this lib and expose two utility functions, like: `const { mockNow, unmockNow } = require('jest-mock-now)`.
What do you think?

**Comment by mattiaerre** [comment]
Hi @MicheleBertoli very good point. If this was a library used in a production bundle I would take your suggestion and add some utility methods but in this case I am not sure if it is worth it because:

- As a mock function a user can still benefit from other mock functionality. 

- Attaching this mock to Date.now exposes it anyway.

- This is a library used to help w/ tests and I'm not sure what is the right approach on this context so that I opted for the more relaxed one.

What do you think about this? Does it sound reasonable to you?

Thanks,

**Comment by MicheleBertoli** [comment]
100% agree.

**Comment by mattiaerre** [comment]
splendid thanks @MicheleBertoli I will merge #3 and close this issue after I publish v1.1.0

// cc @just-boris

**Comment by mattiaerre** [comment]
v1.1.0 [published](https://www.npmjs.com/package/jest-mock-now)

// cc @MicheleBertoli @just-boris
